_BASE_: "../Cityscapes-SemanticSegmentation/Base-DeepLabV3-OS16-Semantic.yaml"
MODEL:
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
    FREEZE_AT: 5
  RESNETS:
    DEPTH: 101
    NORM: "BN"
    OUT_FEATURES: ["res2", "res5"]
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "DeepLabV3PlusHead"
    IN_FEATURES: ["res2", "res5"]
    PROJECT_FEATURES: ["res2"]
    PROJECT_CHANNELS: [48]
    NORM: "BN"
    COMMON_STRIDE: 4
    NUM_CLASSES: 4
    LOSS_TYPE: "cross_entropy_weighted"
SOLVER:
  BASE_LR: 0.00001
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMS_PER_BATCH: 1
  MAX_ITER: 150000
  WARMUP_ITERS: 100
INPUT:
  FORMAT: "RGB"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATASETS:
  TRAIN: ("carte_train",)
  TEST: ("carte_val",)
TEST:
  EVAL_PERIOD: 100
